source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'DoseNet' do
    pod 'SwiftSpinner', '~> 0.8'
    pod 'Alamofire', '~> 3.0'
    pod 'JLToast', '~> 1.3'
    pod 'Charts', '~> 2.1.6'
end

